development:
  adapter: postgresql
  host: <%= ENV['DB_HOST_DEV'] %>
  encoding: unicode
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  adapter: postgresql
  host: <%= ENV['DB_HOST_TEST'] %>
  encoding: unicode
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  adapter:  postgresql
  database: gitz_production
  encoding: unicode
  pool:     5
  username: gitz