development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: gitz2_development

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: gitz2_test

production:
  adapter:  postgresql
  database: gitz_production
  encoding: unicode
  pool:     5
  username: gitz